version: '3'
services:
  nginx:
    restart: always
    build: ./src/nginx/
    ports:
      - 80:80
    depends_on:
      - editor
  editor:
    restart: always
    build: ./src/editor
    depends_on:
      - state
    read_only: true
  state:
    restart: always
    build: ./src/state
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    restart: always
    image: redis
