version: '3'
services:
  editor:
    restart: always
    image: gcr.io/purly-sandbox/editor:0.1.0-dev2
    ports:
      - 80:8000
    depends_on:
      - state
    environment:
      - PURLY_SERVER_HOST=state
      - PURLY_SERVER_PORT=8000
    read_only: true
  state:
    restart: always
    image: gcr.io/purly-sandbox/state:0.1.0-dev2
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    ports:
      - 8000:8000
  redis:
    restart: always
    image: redis
    ports:
      - 6379:6379
