apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: editor
  name: editor
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: editor
    spec:
      containers:
      - env:
        - name: PURLY_SERVER_HOST
          value: state
        - name: PURLY_SERVER_PORT
          value: "8000"
        image: gcr.io/purly-sandbox/editor:0.1.0-dev2
        name: editor
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
